name: appli_gp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  lottie: ^3.1.3
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.4+4
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.26
  date_format_field: ^0.1.0
  input_quantity: ^2.5.0
  date_format: ^2.0.9
  flag: ^7.0.0
  intl: ^0.19.0


  flutter_inappwebview: ^6.1.5
  currency_picker: ^2.0.9
  async: ^2.8.2

  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  shared_preferences: ^2.0.13
  firebase_messaging: ^15.1.3
  http: ^1.2.2

  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  google_maps_flutter: ^2.2.0

  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2

  flutter_osm_plugin: ^1.3.5
  flutter_polyline_points: ^2.1.0
  location: ^7.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets section for including images and other resources in your app.
  assets:
    - assets/images/camion-de-livraison.png
    - assets/images/images.png
    - assets/lottie/lot1.json
    - assets/lottie/lot2.json
    - assets/lottie/lot3.json
    - assets/lottie/lot4.json
    - assets/lottie/lot5.json
    - assets/lottie/lot6.json
    - assets/lottie/lot7.json
    - assets/lottie/paymentpurple.json
    - assets/lottie/delivery.json
    - assets/lottie/delivery1.json
    - assets/lottie/truck.json
    - assets/lottie/truck2.json
    - assets/lottie/track1.json
    - assets/lottie/track2.json
    - assets/lottie/lotcarte.json
    - assets/images/poids.jpeg
    - assets/images/produit.jpeg
    - assets/images/chaussure1.jpeg
    - assets/images/enveloppe.jpeg
    - assets/images/top_background.png
    - assets/images/top_background1.png
    - assets/images/top_background2.png
    - assets/images/search_icon.png
    - assets/images/password.png
    - assets/images/name.png
    - assets/images/appel.png
    - assets/images/notification.png
    - assets/images/video_call.png
    - assets/images/voice_call.png
    - assets/images/logo.png
    - assets/images/communaute.png
    - assets/images/carte-didentite.png
    - assets/images/marque-demplacement.png
    - assets/images/home.png
    - assets/images/home2.png
    - assets/images/home3.png
    - assets/images/ville.png
    - assets/images/pays.png
    - assets/images/ic_1.png
    - assets/images/ic_2.png
    - assets/images/ic_3.png
    - assets/images/ic_4.png
    - assets/images/ic_5.png
    - assets/images/ic_6.png
    - assets/images/ic_7.png
    - assets/images/ic_8.png
    - assets/images/btn_arraw1.png
    - assets/images/email.png
    # You can add other images inside this folder.

  # Fonts section to define custom fonts (if needed)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
