name: appli_gp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  lottie: ^3.1.2
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.4+4
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.26

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets section for including images and other resources in your app.
  assets:
    - assets/flags/usa_flag.png
    - assets/flags/senegal_flag.png
    - assets/flags/france_flag.png
    - assets/flags/uk_flag.png
    - assets/flags/korea_flag.png
    - assets/flags/china_flag.png
    - assets/images/reviewer.jpg
    - assets/images/avatar1.jpg
    - assets/images/avatar2.jpg
    - assets/images/avatar3.png
    - assets/images/colispro.png
    - assets/images/gp.jpg
    - assets/images/camion-de-livraison.png
    - assets/images/camion-de-livraison.gif
    - assets/images/lovepik.png
    - assets/images/p.jpg
    - assets/images/Sanstitre.jpg
    - assets/images/images.png
    - assets/images/GP Express.png
    - assets/images/GP Express(1).png
    - assets/images/GP Express(2).png
    - assets/images/GP Express(3).png
    - assets/images/GP Express(4).png
    - assets/images/GP Express(5).png
    - assets/lottie/lot1.json
    - assets/lottie/lot2.json
    - assets/lottie/lot3.json
    - assets/lottie/lot4.json
    - assets/lottie/lot5.json
    - assets/lottie/lot6.json
    - assets/lottie/lot7.json
    - assets/lottie/lotcarte.json
    # You can add other images inside this folder.

  # Fonts section to define custom fonts (if needed)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
